version: '3.7'

services:
  master:
    build: .
    hostname: mysql-master
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  slave-1:
    build: .
    hostname: mysql-slave-1
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  client:
    image: mysql
    command:
      - sleep
      - inf
